name: sun_point
description: sun point


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: 3.0.10
  retrofit: ^1.3.4+1

  #state_manager
  flutter_bloc: 6.1.1
  equatable: 1.2.5

  #data
  freezed_annotation: 0.12.0
    #database
  moor_flutter: ^3.1.0

  #DI
  koin: ^0.14.0

dependency_overrides:
  analyzer: '0.39.14'


dev_dependencies:
  mockito: 4.1.0

  #codegenerators
  freezed: 0.12.1
  moor_generator: ^3.3.1
  retrofit_generator: any
  json_serializable: 3.3.0
  json_annotation: 3.0.1

  flutter_test:
    sdk: flutter
  build_runner: '>=1.0.0 <2.0.0'


flutter:


  uses-material-design: true
